// import Home from './home/home'
export { Home } from './home/home'
export { Dock } from './dock/dock'
export { Container } from './container/container'
export { Category } from './category/category'
export { Product } from './product/product'
export { Sale } from './sale/sale'